<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5e52c8d6-87a3-4dee-a89b-8ffd85bb765b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='AppModuleTileSec_1_Item_2']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Client Engage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Client Engage\r\nClient Engage Unified Interface App\r\n2 of 5&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c327e45-de86-436d-9ef2-33637b4a2a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>app-icon</value>
      <webElementGuid>b9171779-a218-482e-b8f1-915b3bc26f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>ofs_/Images/ObjectWay_w.svg</value>
      <webElementGuid>0fe9c0ca-4cbf-4bdf-a146-fdf2b58ce431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Client Engage</value>
      <webElementGuid>596e14e5-b9a7-4442-a73e-b54460cfd64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppModuleTileSec_1_Item_2&quot;)/div[1]/img[1]</value>
      <webElementGuid>e4c88638-dab4-4894-954b-365bfb34163f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Apps/iframe_Add new records to Microsoft Dynamic_3a2fba</value>
      <webElementGuid>30c2522f-3106-4476-9a1f-07f42216ed7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='AppModuleTileSec_1_Item_2']/div/img</value>
      <webElementGuid>1809b134-0000-423d-865c-1d9c3acd4901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Client Engage']</value>
      <webElementGuid>ec59fdd6-196a-43be-aaac-3f90fbd52d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/img</value>
      <webElementGuid>c83d67d0-b6b4-48da-9da2-66683f7edf66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'ofs_/Images/ObjectWay_w.svg' and @alt = 'Client Engage']</value>
      <webElementGuid>8c99d97c-b0ba-477a-aa1c-ea006f0c343c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
