<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apps</name>
   <tag></tag>
   <elementGuidId>c30e4c1f-8d79-4b43-ad71-d6cd8fad4e16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav_app_modules']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav_app_modules</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Apps&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d3f2075-9751-468f-b926-75eba1f66185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-rowBody normal</value>
      <webElementGuid>49f8f19d-1897-46f1-aea7-1a247fdbe0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav_app_modules</value>
      <webElementGuid>6c62bff6-130f-4183-af65-5e67abe41500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>b6e7f660-bc45-4dcd-880a-8c2df9de013d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apps</value>
      <webElementGuid>d8af2af1-0945-4a88-a388-07e9c839a449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/OFSCRMWealthQA/%7B638506737500000102%7D/WebResources/msdyn_appmanagementcontrol</value>
      <webElementGuid>2d5e3182-0036-4557-be1f-5d8ebe58e179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>3a403525-f7e9-4f01-8f12-fce30f17a385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iscontextmenuenabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7b698bba-02ce-4201-8463-cf828e6955c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apps</value>
      <webElementGuid>7fed00cc-c65f-4a1d-a4b2-4eb776ac7284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_app_modules&quot;)</value>
      <webElementGuid>e3a04a69-7fee-4e90-b4be-f5984a83fe31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav_app_modules']</value>
      <webElementGuid>c4e557ca-3856-49a7-ad27-e4b87baae691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detailActionGroupControl']/ul/li[5]/span/span/span/span/ul[2]/li/a</value>
      <webElementGuid>172f8d09-4364-4c2d-b2b3-5794e147e161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interactive Service Hub'])[1]/following::a[1]</value>
      <webElementGuid>bc92c22f-60e8-4811-ae6d-00f7f8745b98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application'])[1]/following::a[2]</value>
      <webElementGuid>10e66a3c-2e43-4092-bf2c-578d98da44bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upgrade Logs'])[1]/preceding::a[1]</value>
      <webElementGuid>d23537cf-6623-407a-bd1d-c638ca4f3869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/OFSCRMWealthQA/%7B638506737500000102%7D/WebResources/msdyn_appmanagementcontrol')]</value>
      <webElementGuid>7298880b-04ad-427e-bffc-08003269578d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span/span/span/span/ul[2]/li/a</value>
      <webElementGuid>67ec540c-8231-46ad-9ddf-6c94da0bb648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav_app_modules' and @title = 'Apps' and @href = '/OFSCRMWealthQA/%7B638506737500000102%7D/WebResources/msdyn_appmanagementcontrol' and (text() = 'Apps' or . = 'Apps')]</value>
      <webElementGuid>a16139b5-d79e-4686-94b2-6c6cfc60f8f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
