<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Customer Service Representative Social _cda41a</name>
   <tag></tag>
   <elementGuidId>c70b795c-6f36-41a0-8293-bc48c35b10a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dummyDashboardReflowDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dummyDashboardReflowDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dummyDashboardReflowDiv</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9caf21e5-1bd8-46ea-b366-0c101f6fc643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dummyDashboardReflowDiv</value>
      <webElementGuid>6fa060db-70ca-440c-a850-834a207f2dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dummyDashboardReflowDiv&quot;)</value>
      <webElementGuid>909d8289-8404-4ebb-901b-ae6dc84d7bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>cdb9abac-998c-4973-9690-5e0d90c69ee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='dummyDashboardReflowDiv']</value>
      <webElementGuid>39ec1736-c233-423a-86bf-4ca6847bee10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dummyDashboardReflowWhiteDiv']/div</value>
      <webElementGuid>43014de8-8ec5-4daa-8e79-bdbb060c7adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>1b52c7d0-d8bd-4468-8c13-41efa3ca29a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'dummyDashboardReflowDiv']</value>
      <webElementGuid>9f7984f6-f91f-4f18-91f9-c43d8574104f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
