<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_Chart1_vizIframe</name>
   <tag></tag>
   <elementGuidId>79a96a24-b45b-4599-9727-a51a73b5e52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='Chart1_vizIframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Chart1_vizIframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;Chart1_vizIframe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>6022c410-0ca3-4463-912f-c8cb3b62d9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Chart1_vizIframe</value>
      <webElementGuid>f26131d5-3cd5-4fb5-8980-c7aab323fb34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cases&amp;#32;by&amp;#32;SLA&amp;#32;Status&amp;#32;Over&amp;#32;Week</value>
      <webElementGuid>855e3a0b-8688-4ef2-a78b-8c04049c7ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b0c4a4d1-f168-4095-9ce3-7737d3250812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e1123704-0eed-4e3b-a0d2-051e2b5026bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Chart1_vizIframe</value>
      <webElementGuid>726479f5-c6b6-47b7-bbbe-00aa84012297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gridid</name>
      <type>Main</type>
      <value>Chart1</value>
      <webElementGuid>a2b351bf-204d-4f31-b32e-f617d3da4d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Chart1_vizIframe&quot;)</value>
      <webElementGuid>80006100-041d-41eb-8433-6371dd8bae89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>6c823e53-d325-498c-beea-a3c0105de6b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='Chart1_vizIframe']</value>
      <webElementGuid>a9f17ca7-b64f-469a-8f4f-45a21e6d4d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contentSpan']/iframe</value>
      <webElementGuid>ededb0d9-9ed1-45f2-81a4-e140e56ae8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/iframe</value>
      <webElementGuid>dfb04e7b-41b0-4324-95f0-796c1efd567f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'Chart1_vizIframe' and @title = 'Cases&amp;#32;by&amp;#32;SLA&amp;#32;Status&amp;#32;Over&amp;#32;Week' and @name = 'Chart1_vizIframe']</value>
      <webElementGuid>32aaf5e4-a536-4335-b0de-a69ba01fe81b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
