<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Loading_WebResource_PersonalWall</name>
   <tag></tag>
   <elementGuidId>d17a1899-b1b2-49f4-9e3f-d5797f000d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='WebResource_PersonalWall']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WebResource_PersonalWall</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;WebResource_PersonalWall&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>729bfd17-2187-4340-8ae1-8e08fe037236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>922f3481-37eb-4453-8faf-d88b0946692a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebResource_PersonalWall</value>
      <webElementGuid>d244f293-89e8-4f7a-bfc5-48bd45365605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WebResource_PersonalWall</value>
      <webElementGuid>73c668b6-5524-4285-9f69-64cf1a3d8e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-Custom</value>
      <webElementGuid>9ae7b812-6f9f-4710-8875-a5806c9cc129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delayinitialize</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00fe5923-5ed5-4bbb-b36f-daceac3fd15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f1a01e0-22dc-4e49-9300-4c75fae5e058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/OFSCRMWealthQA/%7B638507212180000102%7D/WebResources/msdyn_/PersonalWall.htm</value>
      <webElementGuid>d08fe529-3967-4889-976e-aa7113811482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>f632b181-269e-4f47-b7ff-89e3b96fe8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e09c9362-7520-4e67-911b-276327a0ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebResource_PersonalWall&quot;)</value>
      <webElementGuid>d147b2c4-0a71-49d4-ab49-be58f03dd7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>ff8d1f61-89c0-4622-8e03-14eeb3f23754</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='WebResource_PersonalWall']</value>
      <webElementGuid>d4662b57-3b90-4342-9d7b-7b1fe4d9195e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WebResource_PersonalWall_d']/span/iframe</value>
      <webElementGuid>cf4dd6da-a0fc-4ecb-a629-bf855ce6184a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/iframe</value>
      <webElementGuid>a50068c8-7a90-4433-b9d1-c0df3fd0010e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'WebResource_PersonalWall' and @name = 'WebResource_PersonalWall']</value>
      <webElementGuid>9546bcc8-dafe-47ad-8f91-acc5ea0d0c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
