<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Refresh all components of the dashbo_94d0bd</name>
   <tag></tag>
   <elementGuidId>9943632c-646b-4bac-a972-7d943533bdee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='contentIFrame0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentIFrame0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;contentIFrame0&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c529f192-536f-476f-bdfe-80e924717e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8362874-c49f-42c6-8c19-2e7b1f8ea9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentIFrame0</value>
      <webElementGuid>f7f5c011-658a-406c-a50e-94339568e627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentIFrame0</value>
      <webElementGuid>0a08506e-a068-47e0-a5cb-5ad99ce1970b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Content Area</value>
      <webElementGuid>183e491f-1d28-45e6-b95e-b2ff61807469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentIFrame0&quot;)</value>
      <webElementGuid>2f7c5608-f0a1-41b9-bff1-2586946e0a1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='contentIFrame0']</value>
      <webElementGuid>86e362c9-9b7d-478b-b41c-04fff424f6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='crmContentPanel']/iframe</value>
      <webElementGuid>017284bb-7b9b-4f63-9034-feaec90f9df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b0efaab3-169c-4f3c-a9de-ed027f399a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentIFrame0' and @name = 'contentIFrame0' and @title = 'Content Area']</value>
      <webElementGuid>e0ecd002-5232-4a78-8df5-342731f3416f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
