<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>a5555a42-09aa-4004-a030-e2a3c8b58dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='navTabLogoTextId']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Microsoft Dynamics 365&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Microsoft Dynamics 365&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>85657fca-e0d8-4d5a-b029-0bc9d9f6b653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_static/oobwebresource/Theme_NavBarLogo.png</value>
      <webElementGuid>a7486d92-755e-4533-ba22-e6bde8024496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Microsoft Dynamics 365</value>
      <webElementGuid>6db74b7f-5573-4f38-8732-f11670bd80f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a990eb2a-649b-4814-9c73-02c63b350d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navTabLogoTextId&quot;)/img[1]</value>
      <webElementGuid>69e2b807-5f3c-4ba2-9b13-fe6e5da4c96f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='navTabLogoTextId']/img</value>
      <webElementGuid>054ca099-840e-416e-8db8-aab20da73bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Microsoft Dynamics 365']</value>
      <webElementGuid>0815ac74-ebbb-41ef-982c-40c5885384dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cb17ceb8-ca72-4bb4-a7e5-f5a5889e8a15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Microsoft Dynamics 365' and @src = '/_static/oobwebresource/Theme_NavBarLogo.png']</value>
      <webElementGuid>cddcd0f6-d50c-40e0-9d38-131257decc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Settings']/span/span/img</value>
      <webElementGuid>7e4db542-2c04-471e-b9f8-94b6e536f386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Settings']</value>
      <webElementGuid>e0a32f2b-feed-423d-9ee8-e40fc8f39a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/a/span/span/img</value>
      <webElementGuid>b9d20d2f-7f4b-4d17-bfa3-e0a17e73f119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_imgs/NavBar/ActionImgs/NavTile_icon_Settings_85x71.png?ver=-1441651920' and @alt = 'Settings']</value>
      <webElementGuid>9c863071-2ab1-4522-8b13-8344ee00f56a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
