<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>8eb88cdd-f715-405d-8db9-8e81bdf13eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='rightNavLink']/span/img)[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.rightNavLinkImg.keyboardFocusClass > img[alt=&quot;Go to next page&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#detailActionGroupControl_rightNavContainer >> internal:role=button[name=&quot;Go to next page&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0d349eb-cadb-407f-ad26-b6ec38e67cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_imgs/NavBar/NavGalleryArrowRight.png</value>
      <webElementGuid>3d7b7a8f-dc78-4ad9-9f14-95fb0be904b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Go to next page</value>
      <webElementGuid>5496dec2-0d11-499e-b97b-3e45ce3ac9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>d8beb3ab-4b33-43a3-a47b-74b9d533ce12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailActionGroupControl_rightNavContainer&quot;)/a[@id=&quot;rightNavLink&quot;]/span[@class=&quot;rightNavLinkImg keyboardFocusClass&quot;]/img[1]</value>
      <webElementGuid>f2c80817-ac7f-4066-9096-672c3024e7ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='rightNavLink']/span/img)[2]</value>
      <webElementGuid>4558934f-28db-4c78-bacd-4a393e1d7a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Go to next page'])[2]</value>
      <webElementGuid>cafbc0b7-268a-4be6-bf03-867a3e768bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/a/span/img</value>
      <webElementGuid>b22ee7c8-aa16-4a4e-8944-377ece9ab433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_imgs/NavBar/NavGalleryArrowRight.png' and @alt = 'Go to next page']</value>
      <webElementGuid>c5aac991-a0e2-4ede-867e-940eede1338d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
