<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_There are no Cases in this view to create a Cases by SLA Status Over Week chart</name>
   <tag></tag>
   <elementGuidId>74c55bd5-9230-42d7-ba34-82ce2eb9263f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='errorLabel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#errorLabel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;There are no Cases in this view to create a Cases by SLA Status Over Week chart.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>13f2717f-f8d3-4729-9080-e8984b606360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorLabel</value>
      <webElementGuid>df89f534-ac11-4d72-8bce-ce246c965901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>There are no Cases in this view to create a Cases by SLA Status Over Week chart.</value>
      <webElementGuid>8970aa91-cfa0-4ac8-a336-2d45b87ddfae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-Info-Label</value>
      <webElementGuid>4aad2971-3317-4175-9d05-3fd4ba1067b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>There are no Cases in this view to create a Cases by SLA Status Over Week chart.</value>
      <webElementGuid>fcc7e590-94c5-464a-a1f7-ede3c1f8abb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorLabel&quot;)</value>
      <webElementGuid>aa287eae-8d12-4501-9e6d-c76fd3e0699f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Loading_Chart1_vizIframe</value>
      <webElementGuid>bafa62e4-81ea-4053-a058-bfc1686e35a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='errorLabel']</value>
      <webElementGuid>eef7d082-9d20-4bb6-acee-9c823f13b185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='errorDiv']/tbody/tr/td/label</value>
      <webElementGuid>56ee0f2e-96d2-4e92-a0b9-19e03d0ef0bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Refresh Chart'])[1]/preceding::label[1]</value>
      <webElementGuid>de964f0f-7963-4491-bcbb-f59444b5478c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='There are no Cases in this view to create a Cases by SLA Status Over Week chart.']/parent::*</value>
      <webElementGuid>e9a690f6-d811-4e5e-ae38-7af21bbc892b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>44162ecb-0ef9-4400-9f8e-7ec1d1aa249c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'errorLabel' and @title = 'There are no Cases in this view to create a Cases by SLA Status Over Week chart.' and (text() = 'There are no Cases in this view to create a Cases by SLA Status Over Week chart.' or . = 'There are no Cases in this view to create a Cases by SLA Status Over Week chart.')]</value>
      <webElementGuid>61de2cea-d83c-43a1-bdd8-3d45616b399f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
