<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nobr_Administration</name>
   <tag></tag>
   <elementGuidId>3707526c-0595-4a5c-9191-8f89a452546a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nobr.ms-crm-VS-MenuItem-Title.ms-crm-VS-MenuItem-Title-Hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Administration&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nobr</value>
      <webElementGuid>48b86a60-e7de-4651-b05d-98ae501c7145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover</value>
      <webElementGuid>1f6d6ee2-bfae-4ccc-844d-68d2ff11539b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>745e695d-3599-46c0-9f25-fd0750ea7618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;{84b11703-9c34-e611-80c5-20474790ab5c}&quot;)/a[@class=&quot;ms-crm-VS-MenuItem-Anchor ms-crm-VS-MenuItem-Anchor-Hover&quot;]/span[@class=&quot;keyboardFocusClass&quot;]/nobr[@class=&quot;ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover&quot;]</value>
      <webElementGuid>19d8b7dd-97b3-44aa-ab93-231eebb175fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>1bcef1e2-6368-416e-bf0e-a5d131d40e52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr</value>
      <webElementGuid>69bcabef-8009-459b-87e6-f34fd6d4a706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Dashboards'])[1]/following::nobr[1]</value>
      <webElementGuid>7ab4ae89-5485-4c3c-b825-2668b497cba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No dashboards are available.'])[1]/following::nobr[2]</value>
      <webElementGuid>88b702c0-d3ba-4b76-83c1-a2d4f5b27f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Expired Overview'])[1]/preceding::nobr[1]</value>
      <webElementGuid>d7506465-60c5-4b03-ba89-26be493396b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/span/nobr</value>
      <webElementGuid>cf6c9175-5f52-4434-900a-626d3cacbb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nobr[(text() = 'Administration' or . = 'Administration')]</value>
      <webElementGuid>5699cc02-cc73-4f42-a423-1beda56457ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
