<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Client Engage_TabHome</name>
   <tag></tag>
   <elementGuidId>04a74efd-afb6-494c-950e-357ee38d4fc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='TabWEA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TabWEA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#TabWEA</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7cfeaee9-7891-42c7-81de-9bf92481c863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TabWEA</value>
      <webElementGuid>b4efccbd-f505-4359-8698-abecc4a5ee8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TabHome</value>
      <webElementGuid>d90b9bc7-b724-4963-ae8d-a7034a4bd1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navTabButton navTabButtonRight SubAreaNodePadding</value>
      <webElementGuid>019a97d2-8181-46ba-9793-3de35241a175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TabWEA&quot;)</value>
      <webElementGuid>4d250015-64f3-4349-a81b-a6c4413dce68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='TabWEA']</value>
      <webElementGuid>e00c2903-9cb6-4726-b142-e40a04f3317e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navTabGroupDiv']/span[4]/span[2]</value>
      <webElementGuid>3fabaac7-3dba-48b7-82ef-9b4d103bb00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Engage'])[1]/following::span[1]</value>
      <webElementGuid>f11837cc-5a05-4a08-8c86-ac24e7d7a017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboards'])[1]/preceding::span[5]</value>
      <webElementGuid>4ce49521-866c-467e-9187-d5ccbeabadb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ikram Gharsallah'])[1]/preceding::span[36]</value>
      <webElementGuid>87a3935d-7e86-43bd-9ca3-e291d4e35aa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[4]/span[2]</value>
      <webElementGuid>41724f9d-cfa4-49ee-ab4b-2b4ee5c8f099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'TabWEA' and @name = 'TabHome']</value>
      <webElementGuid>e578770c-c363-40ba-8369-ba9935ed7acf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
