<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Case Mix by Incident Type</name>
   <tag></tag>
   <elementGuidId>02f51236-c598-4209-87cf-b6df4f52f76d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@id='chartTitle'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Chart2_paneControl > #paneContent > #toolBarRow > #toolBarCell > #visualizationToolBar > #chartTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;Case Mix by Incident Type&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3e248628-0c67-45c1-b0fe-1bf2847ff785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chartTitle</value>
      <webElementGuid>69b08d0a-87db-48bd-b71e-1eab5cbd8779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-headerchartTitle</value>
      <webElementGuid>c7e020a0-a3d1-4da7-a757-e49038ea3696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>468ad5db-efbf-4ebc-bd7d-d182c9df883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Case Mix by Incident Type</value>
      <webElementGuid>afac3042-7e09-465b-9495-fcd5b2b40b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Case Mix by Incident Type</value>
      <webElementGuid>1e55d010-535f-4817-bfc7-a5d1b5c89b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Chart2_paneControl&quot;)/div[@id=&quot;paneContent&quot;]/div[@id=&quot;toolBarRow&quot;]/div[@id=&quot;toolBarCell&quot;]/div[@id=&quot;visualizationToolBar&quot;]/span[@id=&quot;chartTitle&quot;]</value>
      <webElementGuid>f0638980-fa01-4bef-a583-155336ae479d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>80348df4-260d-40bd-bd80-450e2addef6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@id='chartTitle'])[2]</value>
      <webElementGuid>35d36d9d-d022-4629-806c-17d0f4d7452a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='visualizationToolBar']/span)[3]</value>
      <webElementGuid>f6d7dad5-c4c2-4fd1-a615-b60ba25a32b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Mix by Incident Type'])[1]/following::span[2]</value>
      <webElementGuid>84386f48-58aa-442a-ac2b-95d6e7d0c34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::span[7]</value>
      <webElementGuid>6a12e6bf-ceb5-4a6e-a663-867bc5a6a277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Cases'])[1]/preceding::span[4]</value>
      <webElementGuid>916df4a0-be5c-4ae9-925a-9404f674ad9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[2]/preceding::span[5]</value>
      <webElementGuid>946eefed-a2ef-4d35-9225-661982d0fd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/div/div[2]/div/div/div/div/div/div/span/div/div[2]/div/div/span</value>
      <webElementGuid>da078862-bc80-4a0e-a62b-29cc7704b82b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'chartTitle' and @title = 'Case Mix by Incident Type' and (text() = 'Case Mix by Incident Type' or . = 'Case Mix by Incident Type')]</value>
      <webElementGuid>e7a6ad7a-dc19-4c9c-88b9-2cbf7f7fb760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
