<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_My Active Cases</name>
   <tag></tag>
   <elementGuidId>d36e24a9-ce92-486b-9776-7f1d0e506a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='chartSubTitle']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chartSubTitle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;My Active Cases&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89540a83-2373-414c-b5fa-11a5bc26f91a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chartSubTitle</value>
      <webElementGuid>650db5df-5138-42be-89e6-27d41bf493c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>My Active Cases</value>
      <webElementGuid>581a58d0-ab5d-42d3-bc92-ca31474565a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-headerchartSubTitle</value>
      <webElementGuid>223a66d8-0c7f-464d-8952-55ac5e6ab242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a7eb1a46-bfbe-4518-bae7-f3541094002a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Active Cases</value>
      <webElementGuid>9877eea8-b536-4e8d-b683-eba1efcd4c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Chart1_paneControl&quot;)/div[@id=&quot;paneContent&quot;]/div[@id=&quot;toolBarRow&quot;]/div[@id=&quot;toolBarCell&quot;]/div[@id=&quot;visualizationToolBar&quot;]/span[@id=&quot;chartSubTitle&quot;]</value>
      <webElementGuid>fe169386-f686-46d7-8eb2-7de9d4fed934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>54231b56-8ceb-4ba8-a593-1763530adb17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='chartSubTitle']</value>
      <webElementGuid>74f45dd3-019f-4eba-85f7-5f98a5a8b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visualizationToolBar']/span[2]</value>
      <webElementGuid>b0eaf7a9-f7ad-4f6d-865e-a997676deb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases by SLA Status Over Week'])[2]/following::span[4]</value>
      <webElementGuid>bf175eca-d40b-47be-9a1a-998b7b834961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases by SLA Status Over Week'])[1]/following::span[6]</value>
      <webElementGuid>84d4ef21-ba20-49e7-9aa1-a91c67526eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/preceding::span[1]</value>
      <webElementGuid>0387e8c1-ed89-4c78-ad90-67cdeb8a1728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case Mix by Incident Type'])[1]/preceding::span[4]</value>
      <webElementGuid>a9f1d05e-aeeb-438b-8d2c-6bda46ecc47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Active Cases']/parent::*</value>
      <webElementGuid>1bed5953-3750-4068-b3b0-7d78fd87a8a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span[2]</value>
      <webElementGuid>9fb9ab1c-a74f-4c7b-a797-c074c3d7a1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'chartSubTitle' and @title = 'My Active Cases' and (text() = 'My Active Cases' or . = 'My Active Cases')]</value>
      <webElementGuid>3ba5b422-8287-4215-ad30-ec52246a6272</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
