<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dashboards</name>
   <tag></tag>
   <elementGuidId>5fe2ef61-371a-424b-9b15-fba1b45fad6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Tabnav_dashboards-main']/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navTabButtonText.navTabSplitButtonTextCss.navTabButtonSubAreaText</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Dashboards&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45ad8f1f-6808-4302-98b6-db397888342b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navTabButtonText navTabSplitButtonTextCss navTabButtonSubAreaText</value>
      <webElementGuid>f0da6a1a-9fd9-4839-ab79-ca47455f9f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboards</value>
      <webElementGuid>0c2df4ab-88fb-4ade-a4cd-327db063f68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tabnav_dashboards-main&quot;)/a[@class=&quot;navTabButtonLink&quot;]/span[@class=&quot;navTabButtonLabel keyboardFocusClass&quot;]/span[@class=&quot;navTabButtonText navTabSplitButtonTextCss navTabButtonSubAreaText&quot;]</value>
      <webElementGuid>137f514f-41a7-4b16-bc30-1e281b1810ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Tabnav_dashboards-main']/a/span/span</value>
      <webElementGuid>d1893a2d-135c-4f39-bcbf-a5996b5efb38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Client Engage'])[1]/following::span[9]</value>
      <webElementGuid>9e1ebb5d-f30e-480d-8f65-d83666923938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ikram Gharsallah'])[1]/preceding::span[28]</value>
      <webElementGuid>95f4c0e4-50aa-4f49-b790-6c420e7928c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apps for Dynamics 365'])[1]/preceding::span[34]</value>
      <webElementGuid>9140a9ee-2f01-44db-a785-67be1a234b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dashboards']/parent::*</value>
      <webElementGuid>dcfa5400-678a-44cc-8695-1cda690a1da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/span/a/span/span</value>
      <webElementGuid>0df06183-0b1e-4b14-be15-a89ba48c141d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Dashboards' or . = 'Dashboards')]</value>
      <webElementGuid>3ff77c7e-bb9c-410a-b798-802416ff9412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
