<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Customer Service Representative Social Dashboard</name>
   <tag></tag>
   <elementGuidId>7bd1630e-77cf-4f46-9c23-6d66d95b1706</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dashboardSelectorContainer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dashboardSelectorContainer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Customer Service Representative Social Dashboard Select Dashboard&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1d69e59-c1b8-48c4-a70f-2ff17cc16d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dashboardSelectorContainer</value>
      <webElementGuid>1e2ae66a-7868-4574-b8b1-4b37bd25c3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-View-Name ms-crm-TextAutoEllipsis</value>
      <webElementGuid>0fc2e393-982c-4e6c-8428-393cde2b483e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>menuxml</name>
      <type>Main</type>
      <value>&lt;Menu defaultItem=&quot;{063e7659-05d9-4030-960d-10fe269a5a8b}&quot; userDefaultItem=&quot;&quot; systemDefaultItem=&quot;&quot;>&lt;MenuItem id=&quot;SystemDashboard&quot; display=&quot;System Dashboards&quot; type=&quot;header&quot; />&lt;MenuItem id=&quot;{84b11703-9c34-e611-80c5-20474790ab5c}&quot; display=&quot;Administration&quot; desc=&quot;&quot; tooltip=&quot;Administration&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{4758a6bf-da93-e811-80d6-20474790ab5c}&quot; display=&quot;AML Expired Overview&quot; desc=&quot;&quot; tooltip=&quot;AML Expired Overview&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{0d82d80c-6be0-e811-80d7-20474790ab5c}&quot; display=&quot;Approvals Overview&quot; desc=&quot;&quot; tooltip=&quot;Approvals Overview&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{28ad63f3-9f4f-e811-80d6-20474790ab5c}&quot; display=&quot;Audit Log Dashboard&quot; desc=&quot;&quot; tooltip=&quot;Audit Log Dashboard&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{2e19ef4d-6cb1-ea11-8103-20474790ab5d}&quot; display=&quot;Back Office Exception Management&quot; desc=&quot;&quot; tooltip=&quot;Back Office Exception Management&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{c1e77b77-a7c5-e811-80d7-20474790ab5c}&quot; display=&quot;Customer Activation &amp;amp; Maintenance&quot; desc=&quot;&quot; tooltip=&quot;Customer Activation &amp;amp; Maintenance&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{679f8b3a-4b46-ee11-83a8-20474790ab5d}&quot; display=&quot;Customer Progress &amp;amp; Health Check&quot; desc=&quot;&quot; tooltip=&quot;Customer Progress &amp;amp; Health Check&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{df6afc53-3bfa-e911-80ed-20474790ab5d}&quot; display=&quot;Customer Self Service Requests&quot; desc=&quot;&quot; tooltip=&quot;Customer Self Service Requests&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{338ea94a-8f9f-ea11-a812-000d3a31a607}&quot; display=&quot;Customer Service Agent Dashboard&quot; desc=&quot;&quot; tooltip=&quot;Customer Service Agent Dashboard&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{65e050d3-8b71-4b53-acb5-bb9af83bf384}&quot; display=&quot;Customer Service Manager Dashboard&quot; desc=&quot;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; tooltip=&quot;Customer Service Manager Dashboard&amp;#xA;&amp;#xA;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{4e76815a-1f63-df11-ae90-00155d2e3002}&quot; display=&quot;Customer Service Operations Dashboard&quot; desc=&quot;Shows the key performance indicators for customer service operations.&quot; tooltip=&quot;Customer Service Operations Dashboard&amp;#xA;&amp;#xA;Shows the key performance indicators for customer service operations.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{acb40ffe-a1e0-47d0-a472-799911009df6}&quot; display=&quot;Customer Service Performance Dashboard&quot; desc=&quot;Shows the key performance indicators for the customer service team.&quot; tooltip=&quot;Customer Service Performance Dashboard&amp;#xA;&amp;#xA;Shows the key performance indicators for the customer service team.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{2e3d0841-fa6d-df11-986c-00155d2e3002}&quot; display=&quot;Customer Service Performance Dashboard (original version)&quot; desc=&quot;Shows the key performance indicators for the customer service team.&quot; tooltip=&quot;Customer Service Performance Dashboard (original version)&amp;#xA;&amp;#xA;Shows the key performance indicators for the customer service team.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{6e00802f-8c73-df11-986c-00155d2e3002}&quot; display=&quot;Customer Service Representative Dashboard&quot; desc=&quot;Shows the key performance indicators for a customer service representative.&quot; tooltip=&quot;Customer Service Representative Dashboard&amp;#xA;&amp;#xA;Shows the key performance indicators for a customer service representative.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{063e7659-05d9-4030-960d-10fe269a5a8b}&quot; display=&quot;Customer Service Representative Social Dashboard&quot; desc=&quot;Shows the key performance indicators for a customer service representative.&quot; tooltip=&quot;Customer Service Representative Social Dashboard&amp;#xA;&amp;#xA;Shows the key performance indicators for a customer service representative.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{15e19ce1-819e-4789-a5aa-ea4fe1741568}&quot; display=&quot;Customer Service Representative Social Dashboard (original version)&quot; desc=&quot;Shows the key performance indicators for a customer service representative.&quot; tooltip=&quot;Customer Service Representative Social Dashboard (original version)&amp;#xA;&amp;#xA;Shows the key performance indicators for a customer service representative.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{e4bd939f-acd1-e611-80ca-20474790ab5c}&quot; display=&quot;Desk Manager&quot; desc=&quot;&quot; tooltip=&quot;Desk Manager&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{dcd70787-590b-e811-80d4-20474790ab5c}&quot; display=&quot;Diary dashboard&quot; desc=&quot;&quot; tooltip=&quot;Diary dashboard&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{22ff3430-dae9-e911-80ec-20474790ab5d}&quot; display=&quot;Document Dashboard&quot; desc=&quot;&quot; tooltip=&quot;Document Dashboard&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{0767dbff-9c1f-e711-80cd-20474790ab5c}&quot; display=&quot;Exception Management&quot; desc=&quot;&quot; tooltip=&quot;Exception Management&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{a851c3fc-a467-eb11-8143-20474790ab5d}&quot; display=&quot;Exception Reporting&quot; desc=&quot;&quot; tooltip=&quot;Exception Reporting&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{58e8cfe9-a69f-e711-80d1-20474790ab5c}&quot; display=&quot;Health Status&quot; desc=&quot;&quot; tooltip=&quot;Health Status&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{e175ea06-a9d1-e611-80ca-20474790ab5c}&quot; display=&quot;IM Homepage&quot; desc=&quot;&quot; tooltip=&quot;IM Homepage&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{dce7f3ea-76b2-eb11-817b-20474790ab5d}&quot; display=&quot;Maintenance - Failed Activations&quot; desc=&quot;&quot; tooltip=&quot;Maintenance - Failed Activations&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{af4eee17-24f6-44c6-9875-84600c66f11d}&quot; display=&quot;Maintenance - Failed Activations Additional&quot; desc=&quot;&quot; tooltip=&quot;Maintenance - Failed Activations Additional&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{49509741-bbb8-eb11-817e-20474790ab5d}&quot; display=&quot;Maintenance - Routing Requests&quot; desc=&quot;&quot; tooltip=&quot;Maintenance - Routing Requests&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{9de6d9a5-7863-df11-ae90-00155d2e3002}&quot; display=&quot;Marketing Dashboard&quot; desc=&quot;Shows the day-to-day work related data in marketing. It consolidates the important data to make the day productive for marketing managers.&quot; tooltip=&quot;Marketing Dashboard&amp;#xA;&amp;#xA;Shows the day-to-day work related data in marketing. It consolidates the important data to make the day productive for marketing managers.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{b46aeb74-bf0c-44fb-8158-9575588d1b57}&quot; display=&quot;Marketing Social Dashboard&quot; desc=&quot;Shows the day-to-day work related data in marketing. It consolidates the important data to make the day productive for marketing managers.&quot; tooltip=&quot;Marketing Social Dashboard&amp;#xA;&amp;#xA;Shows the day-to-day work related data in marketing. It consolidates the important data to make the day productive for marketing managers.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{ee50a18b-3f88-df11-8d93-00155db1891a}&quot; display=&quot;Microsoft Dynamics 365 Overview&quot; desc=&quot;Shows an overview of your data in Microsoft Dynamics 365.&quot; tooltip=&quot;Microsoft Dynamics 365 Overview&amp;#xA;&amp;#xA;Shows an overview of your data in Microsoft Dynamics 365.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{5d431800-1270-40e9-a90a-c970556cf0fe}&quot; display=&quot;Microsoft Dynamics 365 Social Overview&quot; desc=&quot;Shows an overview of your data in Microsoft Dynamics 365.&quot; tooltip=&quot;Microsoft Dynamics 365 Social Overview&amp;#xA;&amp;#xA;Shows an overview of your data in Microsoft Dynamics 365.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{1116fd0f-0b5b-e711-80cf-20474790ab5c}&quot; display=&quot;Payment Summary&quot; desc=&quot;&quot; tooltip=&quot;Payment Summary&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{38e5ce97-ba4a-e711-80ce-20474790ab5c}&quot; display=&quot;Payment Transfer Dashboard&quot; desc=&quot;&quot; tooltip=&quot;Payment Transfer Dashboard&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{0ad7569a-c6cd-e811-80d7-20474790ab5c}&quot; display=&quot;Portfolio Activation &amp;amp; Maintenance&quot; desc=&quot;&quot; tooltip=&quot;Portfolio Activation &amp;amp; Maintenance&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{45f88f83-0e67-443b-bd05-81d49719f6b1}&quot; display=&quot;Sales Activity Dashboard&quot; desc=&quot;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; tooltip=&quot;Sales Activity Dashboard&amp;#xA;&amp;#xA;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{2701de60-8f2a-48a4-8262-4a35ca7441fa}&quot; display=&quot;Sales Activity Social Dashboard&quot; desc=&quot;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; tooltip=&quot;Sales Activity Social Dashboard&amp;#xA;&amp;#xA;Shows the day-to-day work related data in sales. It consolidates the important data to make the day productive for salespersons.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{d1f511a8-1ead-e211-bb72-00155da9a201}&quot; display=&quot;Sales Dashboard&quot; desc=&quot;Shows the dashboard used by a mobile sales team.&quot; tooltip=&quot;Sales Dashboard&amp;#xA;&amp;#xA;Shows the dashboard used by a mobile sales team.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{3b5d39a7-b216-e711-80d8-00155d896f83}&quot; display=&quot;Sales Overview Dashboard&quot; desc=&quot;Shows the performance of the sales team. Typical dashboard users are Sales Managers and Sales VPs.&quot; tooltip=&quot;Sales Overview Dashboard&amp;#xA;&amp;#xA;Shows the performance of the sales team. Typical dashboard users are Sales Managers and Sales VPs.&quot; type=&quot;1030&quot; istabletenabled=&quot;True&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{25b754f5-7563-df11-ae90-00155d2e3002}&quot; display=&quot;Sales Performance Dashboard&quot; desc=&quot;Shows the sales performance of the sales team. Typical users of this dashboard are Sales Managers and Sales VPs.&quot; tooltip=&quot;Sales Performance Dashboard&amp;#xA;&amp;#xA;Shows the sales performance of the sales team. Typical users of this dashboard are Sales Managers and Sales VPs.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{656a459e-25b2-45ec-95b4-2cfe1895490b}&quot; display=&quot;Server-Side Synchronization Failures&quot; desc=&quot;Shows the overview of items failed during server-side synchronization .&quot; tooltip=&quot;Server-Side Synchronization Failures&amp;#xA;&amp;#xA;Shows the overview of items failed during server-side synchronization .&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{c378c42a-ed4d-4f60-9d17-f71b8bfb91df}&quot; display=&quot;Server-Side Synchronization Monitoring&quot; desc=&quot;Shows the overview of server-side synchronization including mailbox status, performance, and health. This information is useful for troubleshooting.&quot; tooltip=&quot;Server-Side Synchronization Monitoring&amp;#xA;&amp;#xA;Shows the overview of server-side synchronization including mailbox status, performance, and health. This information is useful for troubleshooting.&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{ece20ef7-c9cd-e811-80d7-20474790ab5c}&quot; display=&quot;Suitability Review&quot; desc=&quot;&quot; tooltip=&quot;Suitability Review&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{557b0d16-5ab6-e611-80c9-20474790ab5c}&quot; display=&quot;Support Overview&quot; desc=&quot;&quot; tooltip=&quot;Support Overview&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;MenuItem id=&quot;{f7f050d2-9223-e711-80cd-20474790ab5c}&quot; display=&quot;User Registrations&quot; desc=&quot;&quot; tooltip=&quot;User Registrations&quot; type=&quot;1030&quot; istabletenabled=&quot;False&quot; iconPath=&quot;/_imgs/DashboardSelector/crm_dashboard.png&quot; />&lt;/Menu></value>
      <webElementGuid>166b9b8d-00ea-4b05-842a-a9e23eb2e8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>defaultitem</name>
      <type>Main</type>
      <value>{063e7659-05d9-4030-960d-10fe269a5a8b}</value>
      <webElementGuid>88aabb3b-7d9c-4def-8f13-2de867dbe6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitem</name>
      <type>Main</type>
      <value>{063e7659-05d9-4030-960d-10fe269a5a8b}</value>
      <webElementGuid>1722c9bb-d0b6-4e8d-9c70-c3917800e2d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>currentitemtype</name>
      <type>Main</type>
      <value>1030</value>
      <webElementGuid>72b468cd-6038-4538-ac91-caab7d6f8a6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>istabletenabled</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>7ac60653-442a-42fc-ad02-3e36f29a2dd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Customer Service Representative Social Dashboard</value>
      <webElementGuid>7c3ec86c-2ed8-4189-b29c-b3efb3a97b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Service Representative Social Dashboard</value>
      <webElementGuid>3ea581e2-f656-423d-9fe0-404276aa6e09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboardSelectorContainer&quot;)</value>
      <webElementGuid>e14e4c02-82da-48f2-8487-9fe51a7196fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>c3061a41-82e0-4437-be80-164de9e7b616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dashboardSelectorContainer']</value>
      <webElementGuid>26b1b956-b2aa-431c-9674-890b7db88b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dashboardSelectorLink']/span</value>
      <webElementGuid>80fb6626-d75e-43f2-ab2f-1e87a1adf025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases by SLA Status Over Week'])[1]/preceding::span[3]</value>
      <webElementGuid>a4c0fddd-fd39-4038-809d-780f2e8cbd01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cases by SLA Status Over Week'])[2]/preceding::span[5]</value>
      <webElementGuid>8806d638-6133-4921-9d0d-83433b9cd738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Service Representative Social Dashboard']/parent::*</value>
      <webElementGuid>c6b706bc-3719-4651-a56b-33305829a6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>691af617-638f-4359-83f5-125d9c15ce7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dashboardSelectorContainer' and @title = 'Customer Service Representative Social Dashboard' and (text() = 'Customer Service Representative Social Dashboard' or . = 'Customer Service Representative Social Dashboard')]</value>
      <webElementGuid>84476cbd-a82e-4e70-89ff-eac2e222c85f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
