<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marketing_navActionButtonIcon</name>
   <tag></tag>
   <elementGuidId>de699e95-a545-431e-afbf-90f277c85476</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='Tabnav_dashboards']/a/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.navTabButtonArrowRight</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6a75c0bf-9333-4b1a-bfb3-a0f42e8c08d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navTabButtonArrowRight</value>
      <webElementGuid>d34111de-eca9-44d7-85f9-967cce3bdb94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>c62fd05d-9aa8-4e58-8fda-9263a6b32107</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tabnav_dashboards&quot;)/a[@class=&quot;navTabButtonLink&quot;]/span[@class=&quot;navTabButtonImageContainer keyboardFocusClass&quot;]/span[@class=&quot;navTabButtonArrowRight&quot;]</value>
      <webElementGuid>9c5a4f14-30de-4f0f-ba8a-6d9429f7cb52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='Tabnav_dashboards']/a/span/span</value>
      <webElementGuid>6aa7d9a3-f0d4-4b82-b685-c39abe0aa2bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[5]/span[2]/a/span/span</value>
      <webElementGuid>579493ee-4f45-4604-bf8e-2a90f115f3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Settings']/span/span</value>
      <webElementGuid>747cf79c-3439-44c0-8188-3c4eab1ec6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::span[3]</value>
      <webElementGuid>8cef9637-5a7d-451f-871b-f843f7b1bc8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::span[7]</value>
      <webElementGuid>82def91c-97f5-42a4-a4b8-4c8c63d224b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Settings'])[1]/preceding::span[1]</value>
      <webElementGuid>edf711e5-f514-47fb-8329-5abe9e856d83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Configuration'])[1]/preceding::span[5]</value>
      <webElementGuid>1d6d8fa2-2b3f-4dda-9d07-ed12dd8f5dc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[4]/li/a/span/span</value>
      <webElementGuid>c70e2e5f-ec01-43e1-a73b-ea52a064e588</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
