<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Administration</name>
   <tag></tag>
   <elementGuidId>6359dd9c-21e1-4267-af8c-31cbd34c1860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ms-crm-VS-MenuItem-Title.ms-crm-VS-MenuItem-Title-Hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Administration&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60333440-c37e-46dd-ba6c-81d97ff15f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>ef598e55-41de-45cf-9bff-bb250c85819a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover</value>
      <webElementGuid>1c629378-c225-4370-8909-1b71aa86aaa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>b7147d2e-3ef5-42fd-b361-4ec9792b736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;{84b11703-9c34-e611-80c5-20474790ab5c}&quot;)/a[@class=&quot;ms-crm-VS-MenuItem-Anchor ms-crm-VS-MenuItem-Anchor-Hover&quot;]/span[@class=&quot;keyboardFocusClass&quot;]/nobr[@class=&quot;ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover&quot;]/span[@class=&quot;ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover&quot;]</value>
      <webElementGuid>1876f892-e1ec-4748-a9e0-fd024185ba00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Customer Service Representa_7a7d3c/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>218767e4-8cf4-4304-b3b7-13b6109e7aca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr/span</value>
      <webElementGuid>e183e9f0-2f42-4fb3-bc5c-af56aa6a18b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Dashboards'])[1]/following::span[5]</value>
      <webElementGuid>34b5cac8-2483-43bf-b2fe-983ce0f37136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No dashboards are available.'])[1]/following::span[10]</value>
      <webElementGuid>cd339ba0-8a57-4363-8bef-df94624e9821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Expired Overview'])[1]/preceding::span[4]</value>
      <webElementGuid>fdb48bd9-3797-4308-8615-9c0c7f27b80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approvals Overview'])[1]/preceding::span[9]</value>
      <webElementGuid>5191dca7-ee3f-4fca-9809-6f4d2847fbfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Administration']/parent::*</value>
      <webElementGuid>e1dc5c79-9bb1-4cd3-a50b-d8c703675756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/span/nobr/span</value>
      <webElementGuid>1786267e-b9c1-4b73-b76d-0edae116a035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Administration' and (text() = 'Administration' or . = 'Administration')]</value>
      <webElementGuid>d9618b56-fe02-4884-81b0-83739bc4a59e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
