<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Recycle IIS</name>
   <tag></tag>
   <elementGuidId>547cabd1-572d-4678-8778-7666c0d0ff85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.alert-js-RefreshDialog-Button.alert-js-RefreshDialog-Button-focus</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Recycle IIS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b292ac8a-a3b1-4ebe-a2d5-efb0ea18c4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5168d158-4821-4f05-a087-1fc81ec3360c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>639fbad8-3a0f-4147-b297-7f526df0d891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-js-RefreshDialog-Button alert-js-RefreshDialog-Button-focus</value>
      <webElementGuid>1468fd6c-dfb0-4aa9-83e5-a0e85b8f202d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Recycle IIS</value>
      <webElementGuid>640e0d50-5cdf-4feb-83fd-0cfe65573f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertJs-tdDialogFooter&quot;)/button[@class=&quot;alert-js-RefreshDialog-Button alert-js-RefreshDialog-Button-focus&quot;]</value>
      <webElementGuid>56f7d397-18b4-4679-9e19-adf3b61990c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f4f242ac-28c4-430c-9edf-9f04ddc471c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='alertJs-tdDialogFooter']/button</value>
      <webElementGuid>ff9ed272-3937-4bc7-8f79-7645afbb2bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You are calling a Recycle of the Application Pool of Middleware'])[1]/following::button[1]</value>
      <webElementGuid>9f2c3744-1652-4ae6-bdf5-41a7eae80e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are You sure?'])[1]/following::button[1]</value>
      <webElementGuid>72d2533e-06e5-4496-916b-d8f04d923937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Recycle IIS']/parent::*</value>
      <webElementGuid>b76af93d-1e6e-4465-8670-53cea2060913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>8947954c-b34b-40f1-8208-cb6d881a3afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Recycle IIS' or . = 'Recycle IIS')]</value>
      <webElementGuid>b40bd9ce-701c-477a-8bdd-2d5f062789e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
