<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_concat(id(, , alertJs-image, , ))_alert_9f289a</name>
   <tag></tag>
   <elementGuidId>4b9eed44-40b9-4947-9b8f-94a88082a88b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='alertJs-image']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#alertJs-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#alertJs-image</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e52c4d7c-9d35-45a9-b9a2-d467b1e1ca78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alertJs-image</value>
      <webElementGuid>6f4b2651-b519-4078-9f24-958bce04a991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert-js-image alert-js-image-tick</value>
      <webElementGuid>6ac600d5-7f2b-4bd3-9d36-7f0b73807743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alertJs-image&quot;)</value>
      <webElementGuid>b5a94ecd-c3e2-4298-9170-c3dd6d7f853f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='alertJs-image']</value>
      <webElementGuid>ba0a0d1c-921f-4df8-9ace-c0c7c6fe6d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='alertJs-imageWrapper']/div</value>
      <webElementGuid>6eac53bb-7f8b-4fec-aefd-73c92c44d6ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>f3ca6a6a-9f46-43a9-9d8d-3a31cef585bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'alertJs-image']</value>
      <webElementGuid>532850d4-266a-4b0b-afcd-81a665f8119f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
