<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , WebResource_HealthCheck, , ))_WebResource_HealthCheck</name>
   <tag></tag>
   <elementGuidId>4c94c2cf-0f97-4f6a-873f-4f2e2c5f5287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='WebResource_HealthCheck']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WebResource_HealthCheck</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;WebResource_HealthCheck&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e0c784df-c1d6-45d4-87fd-5d69cbcfd33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8e8873b4-f720-4ae0-991c-c514b4ecdd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WebResource_HealthCheck</value>
      <webElementGuid>992e5c49-e608-44f6-bb04-2918e0ea17b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WebResource_HealthCheck</value>
      <webElementGuid>8f37613d-a818-45e7-8f50-6fb6bc7095f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-Custom</value>
      <webElementGuid>9fc7afaa-838f-4df0-b11b-24fffe44f388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delayinitialize</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ff084cd4-705c-4115-a0ce-2e4b41b1110d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b5c9038c-d5f8-47f1-b2a5-c10f68a7bb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>url</name>
      <type>Main</type>
      <value>/OFSCRMWealthQA/%7B638507212180000102%7D/WebResources/ofs_/Framework/UI/ofscrmui.loader.html?data=HealthCheck_View_Dashboard&amp;orglcid=1033&amp;orgname=OFSCRMWealthQA&amp;userlcid=1033</value>
      <webElementGuid>94f14801-12a1-4b71-a624-793feff9868f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9fa1880c-9402-4c63-831a-f93ca7d7fd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preload</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>decfa8ac-6f31-4533-87a2-9590bdd6f5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WebResource_HealthCheck&quot;)</value>
      <webElementGuid>292165a7-9706-4e54-8ef8-bf7db12f6808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Administration - Microsoft _57c8cb/iframe_Administration_dashboardFrame</value>
      <webElementGuid>2444c26d-c501-4177-a353-90ba0372e728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='WebResource_HealthCheck']</value>
      <webElementGuid>48aafa37-40ce-4ff7-85b9-05c2925b8080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='WebResource_HealthCheck_d']/span/iframe</value>
      <webElementGuid>b3761391-6129-4787-895d-7bf057e9ec40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8401f02e-9835-4c1b-8a95-34b82dc971a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'WebResource_HealthCheck' and @name = 'WebResource_HealthCheck']</value>
      <webElementGuid>bc096168-68c7-4bc5-a8c3-91b105c0e663</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
