<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nobr_Administration</name>
   <tag></tag>
   <elementGuidId>147f648c-ea26-4d78-b822-430792d9ddd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nobr.ms-crm-VS-MenuItem-Title.ms-crm-VS-MenuItem-Title-Hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;Administration&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nobr</value>
      <webElementGuid>9dee8d6a-0359-4fa5-bf93-81dd0e698f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover</value>
      <webElementGuid>9bb836e1-53e7-4847-8d91-46bc49851e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Administration</value>
      <webElementGuid>bf994779-82a1-4463-9da1-d21596ed641c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;{84b11703-9c34-e611-80c5-20474790ab5c}&quot;)/a[@class=&quot;ms-crm-VS-MenuItem-Anchor ms-crm-VS-MenuItem-Anchor-Hover&quot;]/span[@class=&quot;keyboardFocusClass&quot;]/nobr[@class=&quot;ms-crm-VS-MenuItem-Title ms-crm-VS-MenuItem-Title-Hover&quot;]</value>
      <webElementGuid>def9a904-f46d-41c7-962d-a996cf525db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Dashboards Administration - Microsoft _57c8cb/iframe_Refresh all components of the dashbo_94d0bd</value>
      <webElementGuid>9580af88-bf8c-4b87-8fa2-e06e7c37563b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='{84b11703-9c34-e611-80c5-20474790ab5c}']/a[2]/span/nobr</value>
      <webElementGuid>d3cd0af6-c486-4dcf-b53b-eb1af28af408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Dashboards'])[1]/following::nobr[1]</value>
      <webElementGuid>ee08fc3e-98ba-47da-9fe3-bb2637c572d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No dashboards are available.'])[1]/following::nobr[2]</value>
      <webElementGuid>85787550-a04f-4221-b486-96c82e5de5c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML Expired Overview'])[1]/preceding::nobr[1]</value>
      <webElementGuid>10879e72-d9ff-4bd1-91c1-7d23f87084b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a[2]/span/nobr</value>
      <webElementGuid>71823afb-45f4-4837-addd-f6341ae8a56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nobr[(text() = 'Administration' or . = 'Administration')]</value>
      <webElementGuid>09b1a96a-694e-40af-a45e-cfb288eb2e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
